export const  FETCH_BLOCK_CHAIN_REQUEST = 'FETCH_BLOCK_CHAIN_REQUEST';
export const  FETCH_BLOCK_CHAIN_SUCCESS = 'FETCH_BLOCK_CHAIN_SUCCESS';
export const  FETCH_BLOCK_CHAIN_ERROR = 'FETCH_BLOCK_CHAIN_ERROR';